services:
  nginx-shib:
    image: nginx-shib
    build: .
    container_name: nginx-shib
    network_mode: host
    volumes:
      - ./sites:/etc/nginx/sites-enabled:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped

